spring.datasource.url=jdbc:postgresql://localhost:5434/emtlab
spring.datasource.username=emtlab
spring.datasource.password=emtlab


spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.hibernate.ddl-auto=validate
#debug=true
#logging.level.org.flywaydb=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE